global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node

  - job_name: 'ppe-services'
    static_configs:
      - targets: ['dashboard-service.default.svc.cluster.local:80',
                  'view-stock-service.default.svc.cluster.local:80',
                  'logout-service.default.svc.cluster.local:80']

